[project]
name = "nekolibrarian"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "arcanus>=0.1.0",
    "duckduckgo-search>=8.1.1",
    "mijiaapi>=3.0.3",
    "ncatbot>=4.4.1.post1",
    "pydantic-ai>=1.40.0",
]
